version: 2.1

orbs:
  allure: ayte/allure@0.1.3

jobs:
  test:
    docker:
      - image: circleci/openjdk:15-buster-browsers
        auth:
          username: smirnovigor077
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - allure/install
      - run: cd Framework && mvn test
      - store_test_results:
          path: ./Framework/target/surefire-reports
      - allure/report
          
  build:
    docker:
      - image: circleci/openjdk:15-buster-browsers
        auth:
          username: smirnovigor077
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: cd Framework && mvn -Dmaven.test.skip=true compile

workflows:

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
