version: 2.1
orbs:
  allure: ayte/allure@0.1.3

jobs:
  allure_step:
    docker:
      - image: circleci/openjdk:15-buster-browsers
        auth:
          username: smirnovigor077
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - allure/install
      - run: allure generate
      - run: allure-report
  test:
    parallelism: 2
    docker:
      - image: circleci/openjdk:15-buster-browsers
        auth:
          username: smirnovigor077
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: |
          cd Framework && mvn \
          -Dtest=$(for file in $(circleci tests glob "src/test/java/com/epam/ta/test/**.java" \
          | circleci tests split --split-by=timings); \
          do basename $file \
          | sed -e "s/.java/,/"; \
          done | tr -d '\r\n') \
          -e test
      - store_test_results:
          path: target/surefire-reports

  build:
    docker:
      - image: circleci/openjdk:15-buster-browsers
        auth:
          username: smirnovigor077
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: cd Framework && mvn -Dmaven.test.skip=true compile

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - allure_step:
          requires:
            - test
